import { describe,expect,it,vi } from 'vitest';
import { loadCustomerEmailProviderConfig } from '../../apps/api/src/modules/delivery/infrastructure/customer-email-provider.config.js';
import { CustomerEmailProviderError,HttpCustomerEmailProvider } from '../../apps/api/src/modules/delivery/infrastructure/http-customer-email.provider.js';
const message={to:'buyer@example.com',idempotencyKey:'a'.repeat(64),deliveryRequestId:'00000000-0000-4000-8000-000000000001',part:1,partCount:1,assetStart:1,assetEnd:1,subject:'eSIM',text:'text',html:'<p>html</p>',attachments:[{filename:'qr.png',content:Buffer.from('png'),contentType:'image/png'}]};
describe('VS-R1-024 safe customer email provider adapter',()=>{
 it('defaults to disabled',()=>expect(loadCustomerEmailProviderConfig({})).toMatchObject({mode:'disabled'}));
 it('rejects unknown mode',()=>expect(()=>loadCustomerEmailProviderConfig({YSIM_CUSTOMER_EMAIL_MODE:'oops'})).toThrow());
 it('requires live endpoint and token',()=>expect(()=>loadCustomerEmailProviderConfig({YSIM_CUSTOMER_EMAIL_MODE:'live'})).toThrow());
 it('requires HTTPS for live mode',()=>expect(()=>loadCustomerEmailProviderConfig({YSIM_CUSTOMER_EMAIL_MODE:'live',YSIM_CUSTOMER_EMAIL_ENDPOINT:'http://mail.example/send',YSIM_CUSTOMER_EMAIL_TOKEN:'secret'})).toThrow());
 it('validates timeout bounds',()=>expect(()=>loadCustomerEmailProviderConfig({YSIM_CUSTOMER_EMAIL_TIMEOUT_MS:'50'})).toThrow());
 it('fails closed while disabled',async()=>await expect(new HttpCustomerEmailProvider({mode:'disabled',endpoint:null,token:null,timeoutMs:1000}).send(message)).rejects.toMatchObject({category:'DISABLED'}));
 it('returns stable dry-run receipt without network',async()=>{const request=vi.fn();const provider=new HttpCustomerEmailProvider({mode:'dry-run',endpoint:null,token:null,timeoutMs:1000},request);expect(await provider.send(message)).toEqual(await provider.send(message));expect(request).not.toHaveBeenCalled();});
 it('forwards idempotency key and base64 attachment',async()=>{const request=vi.fn(async()=>({ok:true,status:200,json:async()=>({messageId:' msg-1 '})}));const provider=new HttpCustomerEmailProvider({mode:'live',endpoint:'https://mail.example/send',token:'token',timeoutMs:1000},request);expect(await provider.send(message)).toEqual({messageId:'msg-1'});const init=request.mock.calls[0][1];expect((init.headers as Record<string,string>)['idempotency-key']).toBe(message.idempotencyKey);expect(JSON.parse(init.body as string).attachments[0].content).toBe(Buffer.from('png').toString('base64'));});
 it('classifies 429 and 5xx as retryable',async()=>{for(const status of [429,503]){const provider=new HttpCustomerEmailProvider({mode:'live',endpoint:'https://mail.example/send',token:'token',timeoutMs:1000},async()=>({ok:false,status,json:async()=>({})}));await expect(provider.send(message)).rejects.toMatchObject({category:'RETRYABLE'});}});
 it('classifies other 4xx as permanent',async()=>{const provider=new HttpCustomerEmailProvider({mode:'live',endpoint:'https://mail.example/send',token:'token',timeoutMs:1000},async()=>({ok:false,status:400,json:async()=>({})}));await expect(provider.send(message)).rejects.toMatchObject({category:'PERMANENT'});});
 it('rejects an empty provider receipt',async()=>{const provider=new HttpCustomerEmailProvider({mode:'live',endpoint:'https://mail.example/send',token:'token',timeoutMs:1000},async()=>({ok:true,status:200,json:async()=>({messageId:' '})}));await expect(provider.send(message)).rejects.toMatchObject({category:'INVALID_RECEIPT'});});
 it('redacts request details from transport errors',async()=>{const provider=new HttpCustomerEmailProvider({mode:'live',endpoint:'https://mail.example/send',token:'top-secret',timeoutMs:1000},async()=>{throw new Error('buyer@example.com top-secret');});try{await provider.send(message);}catch(error){expect(error).toBeInstanceOf(CustomerEmailProviderError);expect(String(error)).not.toContain('buyer@example.com');expect(String(error)).not.toContain('top-secret');}});
});
